### ISSUE TITLE
Error when saving content contains emoji

### ISSUE THREAD

**Issue by nhvu1988** [melishev/strapi-plugin-react-editorjs#42]
There's an error while saving content contains emoji likes this

![image](https://user-images.githubusercontent.com/13212737/165243067-fb1737d0-385c-4cd2-b2f0-9462fb0d1e4c.png)

The error from console logs

```
api  | [2022-04-26 07:14:42.047] error: update `pages` set `name` = 'Editor.js', `slug` = 'editor-js', `content` = '{\"time\":1650957200290,\"blocks\":[{\"id\":\"Hwcl9QZ50L\",\"type\":\"header\",\"data\":{\"text\":\"😀Strapi + Editor.js\",\"level\":1}}],\"version\":\"2.23.2\"}', `updated_by_id` = 1, `sitemap_exclude` = false, `updated_at` = '2022-04-26 07:14:42.039' where (`id` = 1) - ER_TRUNCATED_WRONG_VALUE_FOR_FIELD: Incorrect string value: '\xF0\x9F\x98\x80St...' for column 'content' at row 1
api  | Error: ER_TRUNCATED_WRONG_VALUE_FOR_FIELD: Incorrect string value: '\xF0\x9F\x98\x80St...' for column 'content' at row 1
api  |     at Query.Sequence._packetToError (/app/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
api  |     at Query.ErrorPacket (/app/node_modules/mysql/lib/protocol/sequences/Query.js:79:18)
api  |     at Protocol._parsePacket (/app/node_modules/mysql/lib/protocol/Protocol.js:291:23)
api  |     at Parser._parsePacket (/app/node_modules/mysql/lib/protocol/Parser.js:433:10)
api  |     at Parser.write (/app/node_modules/mysql/lib/protocol/Parser.js:43:10)
api  |     at Protocol.write (/app/node_modules/mysql/lib/protocol/Protocol.js:38:16)
api  |     at Socket.<anonymous> (/app/node_modules/mysql/lib/Connection.js:88:28)
api  |     at Socket.<anonymous> (/app/node_modules/mysql/lib/Connection.js:526:10)
api  |     at Socket.emit (node:events:526:28)
api  |     at Socket.emit (node:domain:475:12)
api  |     at addChunk (node:internal/streams/readable:315:12)
api  |     at readableAddChunk (node:internal/streams/readable:289:9)
api  |     at Socket.Readable.push (node:internal/streams/readable:228:10)
api  |     at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
api  |     --------------------
api  |     at Protocol._enqueue (/app/node_modules/mysql/lib/protocol/Protocol.js:144:48)
api  |     at Connection.query (/app/node_modules/mysql/lib/Connection.js:198:25)
api  |     at /app/node_modules/knex/lib/dialects/mysql/index.js:132:18
api  |     at new Promise (<anonymous>)
api  |     at Client_MySQL._query (/app/node_modules/knex/lib/dialects/mysql/index.js:126:12)
api  |     at executeQuery (/app/node_modules/knex/lib/execution/internal/query-executioner.js:37:17)
api  |     at Client_MySQL.query (/app/node_modules/knex/lib/client.js:146:12)
api  |     at Runner.query (/app/node_modules/knex/lib/execution/runner.js:130:36)
api  |     at ensureConnectionCallback (/app/node_modules/knex/lib/execution/internal/ensure-connection-callback.js:13:17)
api  |     at Runner.ensureConnection (/app/node_modules/knex/lib/execution/runner.js:307:20)
api  |     at processTicksAndRejections (node:internal/process/task_queues:96:5)
api  |     at async Runner.run (/app/node_modules/knex/lib/execution/runner.js:30:19)
api  |     at async Object.execute (/app/node_modules/@strapi/database/lib/query/query-builder.js:354:22)
api  |     at async Object.update (/app/node_modules/@strapi/database/lib/entity-manager.js:247:9)
api  |     at async Object.update (/app/node_modules/@strapi/strapi/lib/services/entity-service/index.js:219:18)
api  |     at async Object.<anonymous> (/app/node_modules/@strapi/strapi/lib/services/entity-service/index.js:67:20)
```

**Comment by melishev** [comment]
@nhvu1988 - Most likely this error is related to your database, and not to the plugin itself.

**Comment by nhvu1988** [comment]
@melishev I think so but don't know how to fix it? Do you have any suggestions?

**Comment by nhvu1988** [comment]
I have found the solution, it's strapi issue instead, just add `charset: env('DATABASE_CHARSET', 'utf8mb4')` to config/database.js
```
module.exports = ({ env }) => ({
  connection: {
    client: 'mysql',
    connection: {
      ...
      charset: env('DATABASE_CHARSET', 'utf8mb4')
    },
  },
});
```
